import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField} from '../components'
import PropTypes from 'prop-types'

// Función RenderCards:
// Esta función toma dos propiedades: data (una matriz de objetos) y title (un título).
// Si hay datos en la matriz data, mapea los elementos de la matriz y renderiza un componente Card para cada uno.
// Si no hay datos, muestra el título proporcionado en un encabezado h2.

const RenderCards = ({data, title}) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  );
};

RenderCards.propTypes = {
  data: PropTypes.arrayOf(PropTypes.object), // Assuming each post is an object
  title: PropTypes.string.isRequired,
};

// loading: Estado para controlar si se están cargando los datos.
// allPosts: Estado para almacenar todas las publicaciones.
// searchText: Estado para almacenar el texto de búsqueda introducido por el usuario.
// searchedResults: Estado para almacenar los resultados de búsqueda filtrados.
// searchTimeout: Estado para almacenar el tiempo de espera antes de realizar la búsqueda.
// Función fetchPosts:
// Realiza una solicitud GET para obtener las publicaciones desde la API.
// Actualiza el estado allPosts con los datos obtenidos.
// Efecto useEffect: Llama a fetchPosts cuando el componente se monta para obtener las publicaciones iniciales.

const Home = () => {
    const [loading, setLoading] = useState(false)
    const [allPosts, setAllPosts] = useState(null)

    const [searchText, setSearchText] = useState('')
    const [searchedResults, setSearchedResults] = useState(null)
    const [searchTimeout, setSearchTimeout] = useState(null)

    const fetchPosts = async () => {
        setLoading(true);

        try {
            const response = await fetch('https://image-generator-5s68.onrender.com/api/v1/post', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                }, 
            })
            if(response.ok) {
                const result = await response.json()
                setAllPosts(result.data.reverse())
            }
        } catch (error) {
            alert(error)
        } finally {
            setLoading(false)
        }
    }
    useEffect(() => {
        fetchPosts()
    }, [])


  // Función handleSearchChange:
  // Maneja los cambios en el campo de búsqueda.
  // Limpia el temporizador de búsqueda anterior y establece el nuevo valor de búsqueda.
  // Inicia un temporizador para realizar una búsqueda después de un breve retraso.
  // Filtra las publicaciones basadas en el valor de búsqueda y actualiza searchedResults.

const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    const searchTextValue = e.target.value;
    setSearchText(searchTextValue);
  
    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchTextValue.toLowerCase()) ||
            item.prompt.toLowerCase().includes(searchTextValue.toLowerCase())
        );
        setSearchedResults(searchResult);
      }, 500)
    );
  };

// Renderiza una sección que contiene el contenido de la página.
// Incluye un campo de entrada de búsqueda (FormField) que permite a los usuarios buscar publicaciones.
// Si loading es verdadero, muestra un componente Loader mientras se cargan los datos.
// Si hay un valor en searchText, muestra un mensaje de búsqueda.
// Renderiza las publicaciones usando el componente RenderCards, mostrando los resultados de búsqueda o un mensaje si no hay resultados.
  return (
    <section className='mx-auto max-w-7xl'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>Browse through a collection of imaginative and visually stunning images generated by AI</p>
        </div>

        <div className='mt-16'>
            <FormField 
            labelName='Search posts'
            type='text'
            name='text'
            placeholder='Search posts'
            value={searchText}
            handleChange={handleSearchChange}/>
        </div>
        <div className="mt-10">
        {loading ? (
          <div className="flex items-center justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid grid-cols-1 gap-3 lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>
      
    </section>
  )
}

export default Home
